### ISSUE TITLE
Interesting Characters: Blood in the Boarderlands

### ISSUE THREAD

**Issue by TerrorBlades** [Komioski/WH-Geheimnisnacht#10]
Not really a bug more of a oversite of something that I guess most people will not look for.
Some of the characters in this list are unlanded.
![Blood of the Boarderlands](https://github.com/Komioski/WH-Geheimnisnacht/assets/105604501/05834a83-d1c8-4399-b276-af74e0f221c6)

Not the most important thing but felt I might aswell report it.
Love the mod btw.

**Comment by ManuSwaG** [comment]
The issue has been resolved
